name: razer-control
base: core24
version: '0.2.0'
summary: Razer Laptop Control Revived
description: |
  A Linux userspace application to control Razer Blade laptops. 
  No kernel modules (DKMS) required!
  Features a modern GTK4/libadwaita interface for fan control, power modes, 
  keyboard lighting, and battery health optimization.

grade: stable
confinement: strict

layout:
  /usr/share/razercontrol:
    bind: $SNAP/usr/share/razercontrol

parts:
  razer-control:
    plugin: rust
    source: ../../razer_control_gui
    rust-path: .
    build-packages:
      - libusb-1.0-0-dev
      - libdbus-1-dev
      - libhidapi-dev
      - libgtk-4-dev
      - libadwaita-1-dev
      - libglib2.0-dev
      - libgraphene-1.0-dev
      - libpango1.0-dev
      - libcairo2-dev
      - libgdk-pixbuf-2.0-dev
      - pkg-config
    stage-packages:
      - libusb-1.0-0
      - libdbus-1-3
      - libhidapi-hidraw0
      - libgtk-4-1
      - libadwaita-1-0
      - libglib2.0-0
      - libgraphene-1.0-0
    override-build: |
      craftctl default
      mkdir -p $CRAFT_PART_INSTALL/usr/share/razercontrol
      cp -r data/devices/laptops.json $CRAFT_PART_INSTALL/usr/share/razercontrol/
      mkdir -p $CRAFT_PART_INSTALL/usr/share/applications
      cp data/gui/razer-settings.desktop $CRAFT_PART_INSTALL/usr/share/applications/

apps:
  razer-settings:
    command: bin/razer-settings
    extensions: [gnome]
    plugs: [hidraw, raw-usb, system-observe, hardware-observe, desktop, desktop-legacy, wayland, x11]
  
  razer-cli:
    command: bin/razer-cli
    plugs: [hidraw, raw-usb, system-observe, hardware-observe]

  daemon:
    command: bin/daemon
    daemon: simple
    plugs: [hidraw, raw-usb, system-observe, hardware-observe]
